version: '3'
services:
  chat-app-web:
    container_name: chat-app-web
    networks:
      - chat-app-network
    tty: true
    build:
      context: '../../chat-app-web'
      dockerfile: Dockerfile
    ports:
      - 7896:7896
    environment:
      - VITE_CHAT_SERVER_SOCKET_URL=localhost:7898/
  chat-app-server:
    container_name: chat-app-server
    networks:
      - chat-app-network
    tty: true
    build:
        context: '../../chat-app-server'
        dockerfile: Dockerfile
    ports:
      - 7898:7898
    environment:
      - PORT=7898
networks:
  chat-app-network:
    driver: bridge